### ISSUE TITLE
Hello, I'd like to contribute to and join this organization!

### ISSUE THREAD

**Issue by ahcodes** [slurpcode/join-our-team#48]
Opened an issue as instructed in [here](https://github.com/slurpcode/join-our-team#we-are-a-growing-team-with-big-ideas-and-we-need-the-help-of-others).

I can help/contribute with HTML, CSS, and to a lesser extent with JavaScript and Python. Oh, and with documentation if that is needed as well!

**Comment by jbampton** [comment]
Welcome A.H.  

The invite is now sent :)

**Comment by ahcodes** [comment]
@jbampton Sorry for the newbie question but am I supposed to get a notification for the invite?

**Comment by jbampton** [comment]
Yes you should get an email

**Comment by ahcodes** [comment]
Thanks, I'll check it.
