### ISSUE TITLE
I would like to join the organization

### ISSUE THREAD

**Issue by m0lese** [slurpcode/join-our-team#57]
I've been writing idiomatic Rust code since 2019. Posix Shell scripting since 2018. I have extensive expertise with a wide range of Linux distributions, including Ubuntu, Fedora, Arch, Gentoo, Exherbo, Bedrock, and many others. I'm experienced with a variety of programming languages and DevOPS tools. I've recently been studying and playing with [enso](https://enso.org).

**Comment by jbampton** [comment]
The invite has been sent my friend 👍

**Comment by m0lese** [comment]
Thank you!
