### ISSUE TITLE
Request to Join the Organization

### ISSUE THREAD

**Issue by Chayan-11** [slurpcode/join-our-team#59]
I'm Chayan, a Computer Science enthusiast who's into Open source ! I'm currently a Sophomore pursuing my Bachelors in India and have basic knowledge to code in c and c++ along with basic concepts of Data Structures & Algorithms. I would Like to join this organization and would like to learn and improve my skills. Can I get the Invitation Link?

**Comment by BaseMax** [comment]
Welcome Chayan, @Chayan-11 
We usually use Discord for the communication. hope to see you there.
cc @jbampton

**Comment by jbampton** [comment]
The invite has been sent my friend 👍
