### ISSUE TITLE
Please invite me to the organization

### ISSUE THREAD

**Issue by Susmita-Dey** [slurpcode/join-our-team#66]
I'm a sophomore undergrad CS student. I know Java, C/C++, HTML and CSS, shell programming. I'm currently learning Python and DevOps simultaneously. 
Check out my github profile:- https://www.github.com/Susmita-Dey
I came to know from my friend's github profile.
I would like to join so that I can help the community, improve and learn in public.
Thank you

**Comment by jbampton** [comment]
I have sent the invite now 👍
