### ISSUE TITLE
Request to join the GitHub organization

### ISSUE THREAD

**Issue by cixtor** [slurpcode/join-our-team#78]
Hello, slurpcode.

I read that [you are looking for Go and Rust programmers](https://slurpcode.github.io/join-our-team/). I love both programming languages and am in the look out for new projects to contribute to keep my skills sharp. I have used Go to build complex distributed systems for 9+ years and Rust for approximately 3 years (and counting).

I would love to join this community and collaborate with other Go and Rust enthusiasts.

**Comment by jbampton** [comment]
Welcome.  Sorry for the delay.  The invite is sent 👍
