### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by cronusdmd** [slurpcode/join-our-team#79]
I'm experienced blockchain and web developer.
I would like to join with your team and improve some projects.
Thank you!

**Comment by jbampton** [comment]
The invite is now sent 👍  Welcome

**Comment by gitakileus** [comment]
'm experienced blockchain and web developer.
I would like to join with your team and improve some projects.
Thank you!

**Comment by SimonBaey** [comment]
I'm experienced blockchain and web developer.
I would like to join with your team and improve some projects.
Thank you!
