### ISSUE TITLE
Fix the Arabic README to include the issue link

### ISSUE THREAD

**Issue by jbampton** [slurpcode/join-our-team#96]
Fix the Arabic README to include the issue link like how it is in the other READMEs

https://github.com/slurpcode/join-our-team/blob/main/README_JO.md

**Comment by BaseMax** [comment]
> Fix the Arabic README to include the issue link like how it is in the other READMEs

Which issues?

**Comment by jbampton** [comment]
Please add the new "issue" link in the correct place

<img width="1122" alt="Screen Shot 2022-10-29 at 2 28 30 am" src="https://user-images.githubusercontent.com/418747/198686815-29f7e6d3-3339-4db8-8559-9d9a9deaa478.png">
